"""US Presidential Meetings — ranked list of the most market-moving upcoming
international summits the President will attend (APEC, G20, NATO, etc).

Returns curated, narrative-style entries with:
  - rank (1, 2, 3…)
  - title (e.g. "APEC Summit (Shenzhen, China)")
  - date / end_date
  - market_focus (e.g. "U.S.–China Trade and Tech Sector")
  - financial_impact (multi-sentence paragraph explaining how the meeting
    flows through to specific markets)
  - stocks_to_watch / indexes_to_watch (lists of tickers)

Generated by Claude Sonnet 4.5 since no free API publishes presidential
international travel + market impact analysis in a structured way.
"""
import json
import os
import re
import uuid
from datetime import datetime, timezone

from emergentintegrations.llm.chat import LlmChat, UserMessage

EMERGENT_LLM_KEY = os.environ.get("EMERGENT_LLM_KEY", "")
CACHE_KEY = "presidential_meetings"
CACHE_TTL_HOURS = 24
STALE_CACHE_MAX_HOURS = 168


SYSTEM_PROMPT = """You are a geopolitical-financial analyst. Today is {today}.
Return the TOP-RANKED upcoming international summits & bilateral meetings the
US President will attend between today and {end_date}, ordered by expected
market impact (most market-moving first).

For each meeting, include:
1. APEC, G20, NATO, BRICS-counterpart, UN General Assembly, Camp David trilaterals
2. Major bilateral state visits to/from China, Russia, Saudi Arabia, India, Japan, EU
3. Trade-specific summits (USMCA review, US-EU TTIP successor, China Phase-3)
4. Energy summits (OPEC+ engagement, US-Gulf strategic dialogue)

Provide rich, sentiment-aware "financial_impact" paragraphs in the style of
a Bloomberg morning brief — 3 to 5 sentences explaining the specific market
mechanism (e.g. "spike in chipmaker equities", "swings in crude futures",
"pressure on EUR/USD") rather than vague generalities.

Return ONLY a strict JSON object — no markdown:

{{
  "meetings": [
    {{
      "rank": 1,
      "title": "string (e.g. 'APEC Summit (Shenzhen, China)')",
      "date": "YYYY-MM-DD",
      "end_date": "YYYY-MM-DD or null",
      "location": "string (e.g. 'Shenzhen, China')",
      "market_focus": "string (e.g. 'U.S.–China Trade and Tech Sector')",
      "financial_impact": "3-5 sentence paragraph in Bloomberg-brief style explaining the market mechanism",
      "stocks_to_watch": ["NVDA","AMD","TSM","..."],
      "indexes_to_watch": ["SOXX","SMH","..."]
    }}
  ]
}}

Rank order: highest expected market impact first. Max 10 meetings.
Use realistic, verifiable dates for known summits (APEC = mid-Nov,
G20 = mid-Dec or June, NATO summit = July, UNGA = mid-Sept).
For "stocks_to_watch" list 4-8 tickers. For "indexes_to_watch" list 1-3.
"""


def _extract_json(text: str) -> dict:
    text = text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text)
        text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start == -1 or end == -1:
        raise ValueError("No JSON found")
    return json.loads(text[start : end + 1])


async def _fetch_from_llm(today: datetime, end_date: datetime) -> list[dict]:
    prompt = SYSTEM_PROMPT.format(
        today=today.strftime("%Y-%m-%d (%A)"),
        end_date=end_date.strftime("%Y-%m-%d"),
    )
    chat = LlmChat(
        api_key=EMERGENT_LLM_KEY,
        session_id=f"pres-meetings-{uuid.uuid4().hex}",
        system_message=prompt,
    ).with_model("anthropic", "claude-sonnet-4-5-20250929")
    resp = await chat.send_message(
        UserMessage(text=f"Return the ranked US presidential international meetings from {today.strftime('%Y-%m-%d')} through {end_date.strftime('%Y-%m-%d')} per schema.")
    )
    raw = resp if isinstance(resp, str) else getattr(resp, "content", str(resp))
    parsed = _extract_json(raw)
    meetings = parsed.get("meetings", []) or []
    # Filter past meetings + ensure ranks are sequential
    today_str = today.strftime("%Y-%m-%d")
    upcoming = [m for m in meetings if (m.get("date") or "") >= today_str]
    for i, m in enumerate(upcoming, start=1):
        m["rank"] = i
    return upcoming


async def get_presidential_meetings(db) -> dict:
    """Returns {source, meetings}."""
    now = datetime.now(timezone.utc)
    cached = await db.app_cache.find_one({"key": CACHE_KEY})
    cached_age_h = None
    if cached:
        try:
            cached_at = datetime.fromisoformat(cached["cached_at"].replace("Z", "+00:00"))
            cached_age_h = (now - cached_at).total_seconds() / 3600.0
            if cached_age_h < CACHE_TTL_HOURS:
                return {"source": cached.get("source", "llm"), "meetings": cached.get("meetings", [])}
        except Exception:
            cached_age_h = None

    end_of_year = datetime(now.year, 12, 31, tzinfo=timezone.utc)
    if (end_of_year - now).days < 30:
        end_of_year = datetime(now.year + 1, 6, 30, tzinfo=timezone.utc)

    try:
        meetings = await _fetch_from_llm(now, end_of_year)
        await db.app_cache.update_one(
            {"key": CACHE_KEY},
            {"$set": {
                "key": CACHE_KEY, "source": "llm", "meetings": meetings,
                "cached_at": now.isoformat(),
            }},
            upsert=True,
        )
        return {"source": "llm", "meetings": meetings}
    except Exception:
        pass

    if cached and cached_age_h is not None and cached_age_h < STALE_CACHE_MAX_HOURS:
        return {"source": "stale-llm", "meetings": cached.get("meetings", [])}

    return {"source": "none", "meetings": []}
